site_name: Calculation Docs

theme:
  name: "material"
  #--md-code-hl-function-color

plugins:
  - mkdocstrings

nav:
  -  Calculation Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
